---
name: 🤖 Suggest Emoji in Issue Title

on:
  issues:
    types:
      - opened
      - edited

jobs:
  check-emoji:
    runs-on: ubuntu-latest
    permissions:
      issues: write

    steps:
      - name: 📥 Checkout ws-meta
        uses: actions/checkout@v6

      - name: 📛 Check if title starts with emoji
        uses: ./.github/actions/emoji-title-check
        with:
          title: ${{ github.event.issue.title }}
          mode: comment
          number: ${{ github.event.issue.number }}
          token: ${{ secrets.GITHUB_TOKEN }}
